# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\"\x1e\n\x0bModelUpdate\x12\x0f\n\x07weights\x18\x01 \x03(\x02\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2s\n\x11\x46\x65\x64\x65ratedLearning\x12,\n\x0fSendModelUpdate\x12\x0c.ModelUpdate\x1a\t.Response\"\x00\x12\x30\n\x13SendAggregatedModel\x12\x0c.ModelUpdate\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELUPDATE']._serialized_start=19
  _globals['_MODELUPDATE']._serialized_end=49
  _globals['_RESPONSE']._serialized_start=51
  _globals['_RESPONSE']._serialized_end=78
  _globals['_FEDERATEDLEARNING']._serialized_start=80
  _globals['_FEDERATEDLEARNING']._serialized_end=195
# @@protoc_insertion_point(module_scope)
