# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66l.proto\x12\x02\x66l\"1\n\x0bModelUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x03(\x02\"1\n\rClientUpdates\x12 \n\x07updates\x18\x01 \x03(\x0b\x32\x0f.fl.ModelUpdate\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1c\n\x0b\x44oubleValue\x12\r\n\x05value\x18\x01 \x01(\x01\x32\x85\x04\n\x11\x46\x65\x64\x65ratedLearning\x12\x32\n\x0fSendModelUpdate\x12\x0f.fl.ModelUpdate\x1a\x0c.fl.Response\"\x00\x12\"\n\x05\x43lear\x12\t.fl.Empty\x1a\x0c.fl.Response\"\x00\x12\x32\n\x10GetClientUpdates\x12\t.fl.Empty\x1a\x11.fl.ClientUpdates\"\x00\x12)\n\tAggregate\x12\t.fl.Empty\x1a\x0f.fl.ModelUpdate\"\x00\x12\x37\n\x14PropagateGlobalModel\x12\x0f.fl.ModelUpdate\x1a\x0c.fl.Response\"\x00\x12.\n\x0eGetGlobalModel\x12\t.fl.Empty\x1a\x0f.fl.ModelUpdate\"\x00\x12\x32\n\x12GetAggregationTime\x12\t.fl.Empty\x1a\x0f.fl.DoubleValue\"\x00\x12\x33\n\x13GetBCSubmissionTime\x12\t.fl.Empty\x1a\x0f.fl.DoubleValue\"\x00\x12.\n\x0eReportAccuracy\x12\t.fl.Empty\x1a\x0f.fl.DoubleValue\"\x00\x12\x37\n\x14SetBlockchainStorage\x12\x0f.fl.DoubleValue\x1a\x0c.fl.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELUPDATE']._serialized_start=16
  _globals['_MODELUPDATE']._serialized_end=65
  _globals['_CLIENTUPDATES']._serialized_start=67
  _globals['_CLIENTUPDATES']._serialized_end=116
  _globals['_RESPONSE']._serialized_start=118
  _globals['_RESPONSE']._serialized_end=145
  _globals['_EMPTY']._serialized_start=147
  _globals['_EMPTY']._serialized_end=154
  _globals['_DOUBLEVALUE']._serialized_start=156
  _globals['_DOUBLEVALUE']._serialized_end=184
  _globals['_FEDERATEDLEARNING']._serialized_start=187
  _globals['_FEDERATEDLEARNING']._serialized_end=704
# @@protoc_insertion_point(module_scope)
