# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fl_pb2 as fl__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendModelUpdate = channel.unary_unary(
                '/fl.FederatedLearning/SendModelUpdate',
                request_serializer=fl__pb2.ModelUpdate.SerializeToString,
                response_deserializer=fl__pb2.Response.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/fl.FederatedLearning/Clear',
                request_serializer=fl__pb2.Empty.SerializeToString,
                response_deserializer=fl__pb2.Response.FromString,
                _registered_method=True)
        self.GetClientUpdates = channel.unary_unary(
                '/fl.FederatedLearning/GetClientUpdates',
                request_serializer=fl__pb2.Empty.SerializeToString,
                response_deserializer=fl__pb2.ClientUpdates.FromString,
                _registered_method=True)
        self.Aggregate = channel.unary_unary(
                '/fl.FederatedLearning/Aggregate',
                request_serializer=fl__pb2.Empty.SerializeToString,
                response_deserializer=fl__pb2.ModelUpdate.FromString,
                _registered_method=True)
        self.PropagateGlobalModel = channel.unary_unary(
                '/fl.FederatedLearning/PropagateGlobalModel',
                request_serializer=fl__pb2.ModelUpdate.SerializeToString,
                response_deserializer=fl__pb2.Response.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/fl.FederatedLearning/GetGlobalModel',
                request_serializer=fl__pb2.Empty.SerializeToString,
                response_deserializer=fl__pb2.ModelUpdate.FromString,
                _registered_method=True)
        self.GetAggregationTime = channel.unary_unary(
                '/fl.FederatedLearning/GetAggregationTime',
                request_serializer=fl__pb2.Empty.SerializeToString,
                response_deserializer=fl__pb2.DoubleValue.FromString,
                _registered_method=True)
        self.GetBCSubmissionTime = channel.unary_unary(
                '/fl.FederatedLearning/GetBCSubmissionTime',
                request_serializer=fl__pb2.Empty.SerializeToString,
                response_deserializer=fl__pb2.DoubleValue.FromString,
                _registered_method=True)
        self.ReportAccuracy = channel.unary_unary(
                '/fl.FederatedLearning/ReportAccuracy',
                request_serializer=fl__pb2.Empty.SerializeToString,
                response_deserializer=fl__pb2.DoubleValue.FromString,
                _registered_method=True)
        self.SetBlockchainStorage = channel.unary_unary(
                '/fl.FederatedLearning/SetBlockchainStorage',
                request_serializer=fl__pb2.DoubleValue.SerializeToString,
                response_deserializer=fl__pb2.Response.FromString,
                _registered_method=True)


class FederatedLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendModelUpdate(self, request, context):
        """Client -> Server: send local update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Orchestrator -> Server: clear stored updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientUpdates(self, request, context):
        """Orchestrator -> Server: fetch raw client updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregate(self, request, context):
        """Leader -> Server: aggregate stored updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateGlobalModel(self, request, context):
        """Leader -> Loser: propagate final global model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Client -> Server: fetch global model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregationTime(self, request, context):
        """New methods for getting timing metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBCSubmissionTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAccuracy(self, request, context):
        """NEW: Server reports its aggregation accuracy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBlockchainStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelUpdate,
                    request_deserializer=fl__pb2.ModelUpdate.FromString,
                    response_serializer=fl__pb2.Response.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=fl__pb2.Empty.FromString,
                    response_serializer=fl__pb2.Response.SerializeToString,
            ),
            'GetClientUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientUpdates,
                    request_deserializer=fl__pb2.Empty.FromString,
                    response_serializer=fl__pb2.ClientUpdates.SerializeToString,
            ),
            'Aggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.Aggregate,
                    request_deserializer=fl__pb2.Empty.FromString,
                    response_serializer=fl__pb2.ModelUpdate.SerializeToString,
            ),
            'PropagateGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateGlobalModel,
                    request_deserializer=fl__pb2.ModelUpdate.FromString,
                    response_serializer=fl__pb2.Response.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=fl__pb2.Empty.FromString,
                    response_serializer=fl__pb2.ModelUpdate.SerializeToString,
            ),
            'GetAggregationTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregationTime,
                    request_deserializer=fl__pb2.Empty.FromString,
                    response_serializer=fl__pb2.DoubleValue.SerializeToString,
            ),
            'GetBCSubmissionTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBCSubmissionTime,
                    request_deserializer=fl__pb2.Empty.FromString,
                    response_serializer=fl__pb2.DoubleValue.SerializeToString,
            ),
            'ReportAccuracy': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAccuracy,
                    request_deserializer=fl__pb2.Empty.FromString,
                    response_serializer=fl__pb2.DoubleValue.SerializeToString,
            ),
            'SetBlockchainStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBlockchainStorage,
                    request_deserializer=fl__pb2.DoubleValue.FromString,
                    response_serializer=fl__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fl.FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fl.FederatedLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/SendModelUpdate',
            fl__pb2.ModelUpdate.SerializeToString,
            fl__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/Clear',
            fl__pb2.Empty.SerializeToString,
            fl__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/GetClientUpdates',
            fl__pb2.Empty.SerializeToString,
            fl__pb2.ClientUpdates.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Aggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/Aggregate',
            fl__pb2.Empty.SerializeToString,
            fl__pb2.ModelUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/PropagateGlobalModel',
            fl__pb2.ModelUpdate.SerializeToString,
            fl__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/GetGlobalModel',
            fl__pb2.Empty.SerializeToString,
            fl__pb2.ModelUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAggregationTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/GetAggregationTime',
            fl__pb2.Empty.SerializeToString,
            fl__pb2.DoubleValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBCSubmissionTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/GetBCSubmissionTime',
            fl__pb2.Empty.SerializeToString,
            fl__pb2.DoubleValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAccuracy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/ReportAccuracy',
            fl__pb2.Empty.SerializeToString,
            fl__pb2.DoubleValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBlockchainStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl.FederatedLearning/SetBlockchainStorage',
            fl__pb2.DoubleValue.SerializeToString,
            fl__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
